### ISSUE TITLE
dueling deployers redux

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/browserid_deployer#13]
Some suspicious stuff happening in IRC the past few minutes. Might not actually be two deployers, might just be one deployer who's very very talkative:

``` bash
persona_deployer        deploying c580f5e - status https://deployer.personatest.org/c580f5e.txt         11:21
persona_deployer        deployment of c580f5e failed.  check logs for deets         11:22
persona_deployer        error while looking for updates.  check logs for deets          11:22
persona_deployer left the room (quit: Quit: node-irc says goodbye).         11:22
persona_deployer [nodebot@moz-14ABC9C8.compute-1.amazonaws.com] entered the room.           11:24
persona_deployer        deploying c580f5e - status https://deployer.personatest.org/c580f5e.txt         11:24
persona_deployer        deployment of c580f5e failed.  check logs for deets         11:24
persona_deployer left the room (quit: Quit: node-irc says goodbye).         11:24
persona_deployer [nodebot@moz-14ABC9C8.compute-1.amazonaws.com] entered the room.           11:25
persona_deployer        error while looking for updates.  check logs for deets          11:25
persona_deployer left the room (quit: Quit: persona_deployer).          11:25
persona_deployer [nodebot@moz-14ABC9C8.compute-1.amazonaws.com] entered the room.           11:26
persona_deployer        deploying c580f5e - status https://deployer.personatest.org/c580f5e.txt         11:26
persona_deployer        deployment of c580f5e failed.  check logs for deets         11:27
persona_deployer        error while looking for updates.  check logs for deets          11:27
persona_deployer left the room (quit: Quit: node-irc says goodbye).         11:27
persona_deployer [nodebot@moz-14ABC9C8.compute-1.amazonaws.com] entered the room.           11:30
persona_deployer        deploying c580f5e - status https://deployer.personatest.org/c580f5e.txt         11:30
persona_deployer        deployment of c580f5e failed.  check logs for deets         11:31
persona_deployer        error while looking for updates.  check logs for deets          11:31
persona_deployer left the room (quit: Quit: node-irc says goodbye).         11:31
persona_deployer [nodebot@moz-14ABC9C8.compute-1.amazonaws.com] entered the room.           11:33
persona_deployer        deploying c580f5e - status https://deployer.personatest.org/c580f5e.txt         11:33
persona_deployer        deployment of c580f5e failed.  check logs for deets         11:34
persona_deployer left the room (quit: Quit: node-irc says goodbye).         11:34
persona_deployer [nodebot@moz-14ABC9C8.compute-1.amazonaws.com] entered the room.           11:34
persona_deployer        error while looking for updates.  check logs for deets          11:34
persona_deployer left the room (quit: Quit: persona_deployer).          11:34
persona_deployer [nodebot@moz-14ABC9C8.compute-1.amazonaws.com] entered the room.           11:36
persona_deployer        deploying c580f5e - status https://deployer.personatest.org/c580f5e.txt 
```

**Comment by jaredhirsch** [comment]
ok, good news/bad news time, and it's all the same news. two deploy_dev processes running, i dunno why or how.

``` bash
[app@ip-10-191-18-206 ~]$ ps ax |grep deploy
 5631 ?        Ss     0:12 node /home/app/node_modules/.bin/forever -a -l /home/app/var/log/deploy_server.js.log start /home/app/code/deploy_server.js
 5632 ?        Sl     1:56 node /home/app/code/deploy_server.js
17666 ?        Sl     0:00 node /home/app/code/deploy_dev.js
17676 ?        Sl     0:00 node /home/app/code/deploy_dev.js
17871 pts/0    S+     0:00 grep deploy
```

I did a `forever stopall`, then `cd git` and `../post-update.sh`, and now we see

``` bash
[app@ip-10-191-18-206 git]$ ps ax | grep deploy
17908 ?        Ss     0:00 node /home/app/node_modules/.bin/forever -a -l /home/app/var/log/deploy_server.js.log start /home/app/code/deploy_server.js
17909 ?        Sl     0:00 node /home/app/code/deploy_server.js
17952 pts/0    S+     0:00 grep deploy
```

Not sure what happened, time to read the logs.

**Comment by jaredhirsch** [comment]
OK, I'm seeing this over and over in the logs:

looks like we are happily installing, then hit some npm errors or something?

``` bash
2013-08-16T19:00:59.173Z: progress: > browserid@1.0.0-b2 postinstall /home/app/browserid_repo
2013-08-16T19:00:59.173Z: progress: > node ./scripts/postinstall.js
2013-08-16T19:00:59.654Z: progress: npm
2013-08-16T19:00:59.655Z: progress: http
2013-08-16T19:00:59.656Z: progress: GET
2013-08-16T19:00:59.656Z: progress: https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
2013-08-16T19:00:59.921Z: progress: npm http 200 https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
2013-08-16T19:01:00.243Z: progress: npm
2013-08-16T19:01:00.244Z: progress: http
2013-08-16T19:01:00.245Z: progress: GET
2013-08-16T19:01:00.245Z: progress: https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
2013-08-16T19:01:00.268Z: progress: npm
2013-08-16T19:01:00.269Z: progress: WARN
2013-08-16T19:01:00.269Z: progress: prefer global
2013-08-16T19:01:00.269Z: progress: node-inspector@0.2.0beta3 should be installed with -g
2013-08-16T19:01:00.286Z: progress: > browserid@1.0.0-b2 postinstall /home/app/browserid_repo
2013-08-16T19:01:00.286Z: progress: > node ./scripts/postinstall.js
2013-08-16T19:01:00.614Z: progress: npm http 200 https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
2013-08-16T19:01:01.206Z: progress: npm
2013-08-16T19:01:01.207Z: progress: WARN
2013-08-16T19:01:01.209Z: progress: prefer global
2013-08-16T19:01:01.209Z: progress: node-inspector@0.2.0beta3 should be installed with -g
2013-08-16T19:01:01.225Z: progress: > browserid@1.0.0-b2 postinstall /home/app/browserid_repo
2013-08-16T19:01:01.225Z: progress: > node ./scripts/postinstall.js
2013-08-16T19:01:01.365Z: progress: fatal error: can't extract git sha from /home/app/browserid_repo
2013-08-16T19:01:01.462Z: error: true
2013-08-16T19:01:02.549Z: progress: reading .awsbox.json
2013-08-16T19:01:02.550Z: progress: attempting to set up VM "login.dev.anosrep.org (c580f5e)"
2013-08-16T19:02:35.939Z: progress: events.js:68
2013-08-16T19:02:35.939Z: progress: throw arguments[1]; // Unhandled 'error' event
2013-08-16T19:02:35.939Z: progress: ^
2013-08-16T19:02:35.943Z: progress: Error: socket hang up
2013-08-16T19:02:35.943Z: progress: at createHangUpError (http.js:1264:15)
2013-08-16T19:02:35.943Z: progress: at Socket.socketOnEnd [as onend] (http.js:1352:23)
2013-08-16T19:02:35.943Z: progress: at TCP.onread (net.js:418:26)
2013-08-16T19:02:35.948Z: progress: fatal error: Error: Command failed:
2013-08-16T19:02:35.948Z: progress: events.js:68
2013-08-16T19:02:35.948Z: progress: throw arguments[1]; // Unhandled 'error' event
2013-08-16T19:02:35.949Z: progress: ^
2013-08-16T19:02:35.949Z: progress: Error: socket hang up
2013-08-16T19:02:35.949Z: progress: at createHangUpError (http.js:1264:15)
2013-08-16T19:02:35.949Z: progress: at Socket.socketOnEnd [as onend] (http.js:1352:23)
2013-08-16T19:02:35.949Z: progress: at TCP.onread (net.js:418:26)
2013-08-16T19:02:35.951Z: error: true
```

then (this is the next logline, nothing removed), we get some kind of other error code, and immediately spawn two deployers:

``` bash
2013-08-16T19:03:01.476Z: checking for updates: received 'error' signal, checking 2 min later.
2013-08-16T19:03:01.477Z: info: checking for updates
2013-08-16T19:03:01.860Z: progress: Already up-to-date.
2013-08-16T19:03:01.873Z: info: latest available sha is c580f5e
2013-08-16T19:03:05.878Z: info: can't get current running code: Timeout resolving login.dev.anosrep.org
2013-08-16T19:03:05.878Z: deployment_begins: {
  "sha": "c580f5e"
}
2013-08-16T19:03:05.889Z: resolved login.dev.anosrep.org -> null
2013-08-16T19:03:05.891Z: info: can't get current running code: Error: connect ECONNREFUSED
2013-08-16T19:03:05.891Z: deployment_begins: {
  "sha": "c580f5e"
}
2013-08-16T19:03:06.167Z: irc error:  { prefix: 'concrete.mozilla.org',
  server: 'concrete.mozilla.org',
  command: 'err_notregistered',
  rawCommand: '451',
  commandType: 'error',
  args: [ 'PRIVMSG', 'You have not registered' ] }
2013-08-16T19:03:07.650Z: progress: > browserid@1.0.0-b2 preinstall /home/app/browserid_repo
2013-08-16T19:03:07.650Z: progress: > node ./scripts/lockdown
2013-08-16T19:03:07.658Z: progress: > browserid@1.0.0-b2 preinstall /home/app/browserid_repo
2013-08-16T19:03:07.658Z: progress: > node ./scripts/lockdown
```

and now, because the 'progress' loglines don't include, say, the pid of the child process, I can't tell how many deployers are deploying. But I assume that's what is happening here.

**Comment by jaredhirsch** [comment]
This is why there are pidfiles, right? To avoid spawning 2 of the same thing? I suppose something like deployer.pid in the directory could be used to ensure we don't get into these recurring situations any longer.

**Comment by jaredhirsch** [comment]
I am unable to repro the issue today. I suspect there were problems with the DNS or AWS APIs, maybe?

At any rate, following historical precedent, I'm closing the issue and avoiding thinking about deployer until the next time I get burned
